# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf452998fbf012b7dd7a1413d5b957b95fa390bcc99422c3c4c6183d2a4ad762238186a15e170713479f3c2a8b0f95a0788dbfd6496ab4410cc82c5e202ad191

test:
  secret_key_base: 25b558a97ea61f2d869e3ad8cdab70bcd58c5c71d6e98a2af7824beda2f3d042eb66b36b6e74cfecc049914b653af3f855c445748527b981ddd6e3d612898a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
